JAVA_VERSION_MIN_SUPPORTED=17
MIN_SUPPORTED_ANDROID_STUDIO_IDE_VERSION=2023.3
MIN_SUPPORTED_INTELLIJ_IDEA_IDE_VERSION=2023.3
OVERRIDDEN_ANDROID_GRADLE_PLUGIN_VERSION=NONE
OVERRIDDEN_JAVA_VERSION=NONE
OVERRIDDEN_KOTLIN_GRADLE_PLUGIN_VERSION=NONE
